/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comp3751_softwareproto.group1_.knig0033_lanc0035_hunt0065;

/**
 *
 * @author d3ath
 */
public class Main_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form tab_security
     */
    public Main_JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        security_B = new javax.swing.JButton();
        report_B = new javax.swing.JButton();
        info_B = new javax.swing.JButton();
        events_B = new javax.swing.JButton();
        map_B = new javax.swing.JButton();
        login_B = new javax.swing.JButton();
        FLINSAFE = new javax.swing.JLabel();
        base_pan = new javax.swing.JPanel();
        security_pan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        report_pan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        info_pan = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        login_pan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        map_pan = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        events_pan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        security_B.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        security_B.setText("Security");
        security_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                security_BActionPerformed(evt);
            }
        });

        report_B.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        report_B.setText("Report");
        report_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_BActionPerformed(evt);
            }
        });

        info_B.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        info_B.setText("Information");
        info_B.setToolTipText("");

        events_B.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        events_B.setText("Events");
        events_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                events_BActionPerformed(evt);
            }
        });

        map_B.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        map_B.setText("Map");

        login_B.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        login_B.setText("Login");
        login_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_BActionPerformed(evt);
            }
        });

        FLINSAFE.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        FLINSAFE.setText("FLINSAFE");

        base_pan.setLayout(new java.awt.CardLayout());

        jLabel1.setText("SECURITY MEMES");

        javax.swing.GroupLayout security_panLayout = new javax.swing.GroupLayout(security_pan);
        security_pan.setLayout(security_panLayout);
        security_panLayout.setHorizontalGroup(
            security_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(security_panLayout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(jLabel1)
                .addContainerGap(741, Short.MAX_VALUE))
        );
        security_panLayout.setVerticalGroup(
            security_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(security_panLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        base_pan.add(security_pan, "card2");

        jLabel2.setText("Report memes");

        javax.swing.GroupLayout report_panLayout = new javax.swing.GroupLayout(report_pan);
        report_pan.setLayout(report_panLayout);
        report_panLayout.setHorizontalGroup(
            report_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report_panLayout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(jLabel2)
                .addContainerGap(691, Short.MAX_VALUE))
        );
        report_panLayout.setVerticalGroup(
            report_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report_panLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel2)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        base_pan.add(report_pan, "card3");

        jLabel4.setText("Infomemes");

        javax.swing.GroupLayout info_panLayout = new javax.swing.GroupLayout(info_pan);
        info_pan.setLayout(info_panLayout);
        info_panLayout.setHorizontalGroup(
            info_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_panLayout.createSequentialGroup()
                .addGap(473, 473, 473)
                .addComponent(jLabel4)
                .addContainerGap(654, Short.MAX_VALUE))
        );
        info_panLayout.setVerticalGroup(
            info_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_panLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel4)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        base_pan.add(info_pan, "card4");

        jLabel5.setText("Login memes");

        javax.swing.GroupLayout login_panLayout = new javax.swing.GroupLayout(login_pan);
        login_pan.setLayout(login_panLayout);
        login_panLayout.setHorizontalGroup(
            login_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_panLayout.createSequentialGroup()
                .addContainerGap(589, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(530, 530, 530))
        );
        login_panLayout.setVerticalGroup(
            login_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_panLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel5)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        base_pan.add(login_pan, "card5");

        jLabel6.setText("map memes");

        javax.swing.GroupLayout map_panLayout = new javax.swing.GroupLayout(map_pan);
        map_pan.setLayout(map_panLayout);
        map_panLayout.setHorizontalGroup(
            map_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(map_panLayout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(jLabel6)
                .addContainerGap(674, Short.MAX_VALUE))
        );
        map_panLayout.setVerticalGroup(
            map_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(map_panLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel6)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        base_pan.add(map_pan, "card6");

        jLabel7.setText("event memes");

        javax.swing.GroupLayout events_panLayout = new javax.swing.GroupLayout(events_pan);
        events_pan.setLayout(events_panLayout);
        events_panLayout.setHorizontalGroup(
            events_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, events_panLayout.createSequentialGroup()
                .addContainerGap(744, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(372, 372, 372))
        );
        events_panLayout.setVerticalGroup(
            events_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(events_panLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel7)
                .addContainerGap(342, Short.MAX_VALUE))
        );

        base_pan.add(events_pan, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(base_pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(517, 517, 517)
                        .addComponent(FLINSAFE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(security_B, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(report_B, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(info_B, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(events_B, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(map_B, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(login_B, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(FLINSAFE, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(login_B, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(map_B, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(events_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(info_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(security_B, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(report_B, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(base_pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void security_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_security_BActionPerformed
        //Deleting panels
        base_pan.removeAll();
        base_pan.revalidate();
        
        //Adding panels
        base_pan.add(security_pan);
        base_pan.revalidate();
        
    }//GEN-LAST:event_security_BActionPerformed

    private void report_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_BActionPerformed
        //Deleting panels
        base_pan.removeAll();
        base_pan.revalidate();
        
        //Adding panels
        base_pan.add(report_pan);
        base_pan.revalidate();
    }//GEN-LAST:event_report_BActionPerformed

    private void login_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_BActionPerformed
        //Deleting panels
        base_pan.removeAll();
        base_pan.revalidate();

        //Adding panels
        base_pan.add(login_pan);
        base_pan.revalidate();
    }//GEN-LAST:event_login_BActionPerformed

    private void events_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_events_BActionPerformed
        //Deleting panels
        base_pan.removeAll();
        base_pan.revalidate();

        //Adding panels
        base_pan.add(events_pan);
        base_pan.revalidate();
    }//GEN-LAST:event_events_BActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FLINSAFE;
    private javax.swing.JPanel base_pan;
    private javax.swing.JPanel base_pan1;
    private javax.swing.JButton events_B;
    private javax.swing.JPanel events_pan;
    private javax.swing.JButton info_B;
    private javax.swing.JPanel info_pan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton login_B;
    private javax.swing.JPanel login_pan;
    private javax.swing.JButton map_B;
    private javax.swing.JPanel map_pan;
    private javax.swing.JButton report_B;
    private javax.swing.JPanel report_pan;
    private javax.swing.JPanel report_pan1;
    private javax.swing.JPanel report_pan2;
    private javax.swing.JPanel report_pan3;
    private javax.swing.JPanel report_pan4;
    private javax.swing.JButton security_B;
    private javax.swing.JPanel security_pan;
    private javax.swing.JPanel security_pan1;
    private javax.swing.JPanel security_pan2;
    private javax.swing.JPanel security_pan3;
    private javax.swing.JPanel security_pan7;
    // End of variables declaration//GEN-END:variables
}
