/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comp3751_softwareproto.group1_.knig0033_lanc0035_hunt0065;

/**
 *
 * @author d3ath
 */
public class Main_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form tab_security
     */
    public Main_JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        security_B = new javax.swing.JButton();
        report_B = new javax.swing.JButton();
        info_B = new javax.swing.JButton();
        events_B = new javax.swing.JButton();
        map_B = new javax.swing.JButton();
        login_B = new javax.swing.JButton();
        base_pan = new javax.swing.JPanel();
        security_pan = new javax.swing.JPanel();
        callsecurity_B = new javax.swing.JButton();
        medicalass_B = new javax.swing.JButton();
        emergen_B = new javax.swing.JButton();
        eventlist_security_JScrollPane = new javax.swing.JScrollPane();
        eventlist_security_List = new javax.swing.JList<>();
        eventlist_security_Label = new javax.swing.JLabel();
        info_security_JScrollPane = new javax.swing.JScrollPane();
        info_security_Text = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        report_pan = new javax.swing.JPanel();
        details_report_jScrollPanel = new javax.swing.JScrollPane();
        details_report_Text = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        report_cancel_B = new javax.swing.JButton();
        report_submit_B = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        info_pan = new javax.swing.JPanel();
        info_text_pan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        login_pan = new javax.swing.JPanel();
        password_Field = new javax.swing.JPasswordField();
        logintosystem_b = new javax.swing.JButton();
        username_Field = new javax.swing.JFormattedTextField();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        rightside_login_pan = new javax.swing.JPanel();
        event_scroll_login_Text = new javax.swing.JTextField();
        importantnews_login_Label = new javax.swing.JLabel();
        info_login_JScrollPane = new javax.swing.JScrollPane();
        info_login_Text = new javax.swing.JTextArea();
        FLINDERSUNIVERSITY = new javax.swing.JLabel();
        map_pan = new javax.swing.JPanel();
        filter1_map_Check = new javax.swing.JCheckBox();
        fliter2_map_Check = new javax.swing.JCheckBox();
        fliter3_map_Check = new javax.swing.JCheckBox();
        fliter4_map_Check = new javax.swing.JCheckBox();
        fliter5_map_Check = new javax.swing.JCheckBox();
        fliter6_map_Check = new javax.swing.JCheckBox();
        fliters_map_Label = new javax.swing.JLabel();
        search_map_Form = new javax.swing.JFormattedTextField();
        search_map_B = new javax.swing.JButton();
        map_map_pan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        events_pan = new javax.swing.JPanel();
        filters_events_Label = new javax.swing.JLabel();
        filter1_events_Check = new javax.swing.JCheckBox();
        fliter2_events_Check = new javax.swing.JCheckBox();
        fliter3_events_Check = new javax.swing.JCheckBox();
        fliter4_events_Check = new javax.swing.JCheckBox();
        fliter5_events_Check = new javax.swing.JCheckBox();
        fliter6_events_Check = new javax.swing.JCheckBox();
        search_events_Form = new javax.swing.JFormattedTextField();
        search_evnets_B = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        FLINSAFE4 = new javax.swing.JLabel();
        FLINSAFE2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        security_B.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        security_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/securityButtonTop/security_bBase.png"))); // NOI18N
        security_B.setOpaque(false);
        security_B.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/securityButtonTop/security_bMouseOver.png"))); // NOI18N
        security_B.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/securityButtonTop/security_bPressed.png"))); // NOI18N
        security_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                security_BActionPerformed(evt);
            }
        });
        getContentPane().add(security_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 160, 100));

        report_B.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        report_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reportButtonTop/report_bBase.png"))); // NOI18N
        report_B.setOpaque(false);
        report_B.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reportButtonTop/report_bMouseOver.png"))); // NOI18N
        report_B.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reportButtonTop/report_bPressed.png"))); // NOI18N
        report_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_BActionPerformed(evt);
            }
        });
        getContentPane().add(report_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 160, 100));

        info_B.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        info_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informationButtonTop/info_bBase.png"))); // NOI18N
        info_B.setToolTipText("");
        info_B.setOpaque(false);
        info_B.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informationButtonTop/info_bMouseOver.png"))); // NOI18N
        info_B.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informationButtonTop/info_bPressed.png"))); // NOI18N
        info_B.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informationButtonTop/info_bPressed.png"))); // NOI18N
        info_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_BActionPerformed(evt);
            }
        });
        getContentPane().add(info_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 198, 100));

        events_B.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        events_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eventsButtonTop/events_bBase.png"))); // NOI18N
        events_B.setOpaque(false);
        events_B.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eventsButtonTop/events_bMouseOver.png"))); // NOI18N
        events_B.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eventsButtonTop/events_bPressed.png"))); // NOI18N
        events_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                events_BActionPerformed(evt);
            }
        });
        getContentPane().add(events_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 160, 100));

        map_B.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        map_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mapButtonTop/map_bBase.png"))); // NOI18N
        map_B.setOpaque(false);
        map_B.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mapButtonTop/map_bMouseOver.png"))); // NOI18N
        map_B.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mapButtonTop/map_bPressed.png"))); // NOI18N
        map_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                map_BActionPerformed(evt);
            }
        });
        getContentPane().add(map_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 160, 100));

        login_B.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        login_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginbuttonTop/login_bBase.png"))); // NOI18N
        login_B.setToolTipText("");
        login_B.setOpaque(false);
        login_B.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginbuttonTop/login_bPressed.png"))); // NOI18N
        login_B.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginbuttonTop/login_bMouseOver.png"))); // NOI18N
        login_B.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginbuttonTop/login_bPressed.png"))); // NOI18N
        login_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_BActionPerformed(evt);
            }
        });
        getContentPane().add(login_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 160, 100));

        base_pan.setLayout(new java.awt.CardLayout());

        security_pan.setMaximumSize(new java.awt.Dimension(1200, 562));
        security_pan.setPreferredSize(new java.awt.Dimension(1200, 562));

        callsecurity_B.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        callsecurity_B.setText("Call Security");
        callsecurity_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callsecurity_BActionPerformed(evt);
            }
        });

        medicalass_B.setFont(new java.awt.Font("Tahoma", 0, 34)); // NOI18N
        medicalass_B.setText("Medical Assistance");
        medicalass_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalass_BActionPerformed(evt);
            }
        });

        emergen_B.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        emergen_B.setText("Emergency Services");
        emergen_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergen_BActionPerformed(evt);
            }
        });

        eventlist_security_List.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eventlist_security_List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        eventlist_security_JScrollPane.setViewportView(eventlist_security_List);

        eventlist_security_Label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        eventlist_security_Label.setLabelFor(eventlist_security_JScrollPane);
        eventlist_security_Label.setText("                         Event List");
        eventlist_security_Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        info_security_Text.setEditable(false);
        info_security_Text.setColumns(20);
        info_security_Text.setRows(5);
        info_security_Text.setText("INFO ABOUT CALLING SECURITY AND SUCH");
        info_security_Text.setBorder(null);
        info_security_Text.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        info_security_Text.setOpaque(false);
        info_security_JScrollPane.setViewportView(info_security_Text);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Security avaliability at this machine");

        jProgressBar1.setToolTipText("");

        javax.swing.GroupLayout security_panLayout = new javax.swing.GroupLayout(security_pan);
        security_pan.setLayout(security_panLayout);
        security_panLayout.setHorizontalGroup(
            security_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(security_panLayout.createSequentialGroup()
                .addGroup(security_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(security_panLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(security_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(medicalass_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(callsecurity_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emergen_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59))
                    .addGroup(security_panLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)))
                .addGroup(security_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eventlist_security_JScrollPane)
                    .addComponent(info_security_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                    .addComponent(eventlist_security_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        security_panLayout.setVerticalGroup(
            security_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, security_panLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(security_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(security_panLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(callsecurity_B, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(medicalass_B, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emergen_B, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(security_panLayout.createSequentialGroup()
                        .addComponent(info_security_JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eventlist_security_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eventlist_security_JScrollPane)))
                .addContainerGap())
        );

        base_pan.add(security_pan, "card2");

        report_pan.setMaximumSize(new java.awt.Dimension(1200, 562));
        report_pan.setPreferredSize(new java.awt.Dimension(1200, 562));

        details_report_Text.setColumns(20);
        details_report_Text.setRows(5);
        details_report_Text.setText("Hey there, things happened here\n");
        details_report_jScrollPanel.setViewportView(details_report_Text);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Please enter the details of the incident");

        report_cancel_B.setText("cancel");
        report_cancel_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_cancel_BActionPerformed(evt);
            }
        });

        report_submit_B.setText("submit");

        jTextField1.setText("jTextField1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Type of incident");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Location");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Time of day");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout report_panLayout = new javax.swing.GroupLayout(report_pan);
        report_pan.setLayout(report_panLayout);
        report_panLayout.setHorizontalGroup(
            report_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report_panLayout.createSequentialGroup()
                .addGroup(report_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(report_panLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(report_submit_B, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(report_cancel_B, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(report_panLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(report_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jComboBox2, 0, 370, Short.MAX_VALUE)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(report_panLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel2))))
                    .addGroup(report_panLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel6))
                    .addGroup(report_panLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addGroup(report_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(details_report_jScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, report_panLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(86, 86, 86)))
                .addGap(31, 31, 31))
        );
        report_panLayout.setVerticalGroup(
            report_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report_panLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(report_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, report_panLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1)
                        .addGap(63, 63, 63)
                        .addGroup(report_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(report_submit_B, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(report_cancel_B, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(report_panLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(details_report_jScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );

        base_pan.add(report_pan, "card3");

        info_pan.setMaximumSize(new java.awt.Dimension(1200, 562));
        info_pan.setPreferredSize(new java.awt.Dimension(1200, 562));
        info_pan.setRequestFocusEnabled(false);

        info_text_pan.setMaximumSize(new java.awt.Dimension(870, 540));
        info_text_pan.setPreferredSize(new java.awt.Dimension(870, 540));
        info_text_pan.setRequestFocusEnabled(false);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane5.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane6.setViewportView(jTextArea5);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout info_text_panLayout = new javax.swing.GroupLayout(info_text_pan);
        info_text_pan.setLayout(info_text_panLayout);
        info_text_panLayout.setHorizontalGroup(
            info_text_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(info_text_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(info_text_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(info_text_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        info_text_panLayout.setVerticalGroup(
            info_text_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(info_text_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(info_text_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(info_text_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("jButton1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Terms and Conditions");

        jButton2.setText("jButton1");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Helpful tips");

        jButton3.setText("jButton1");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Manual");

        jButton4.setText("jButton1");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("FAQ");

        javax.swing.GroupLayout info_panLayout = new javax.swing.GroupLayout(info_pan);
        info_pan.setLayout(info_panLayout);
        info_panLayout.setHorizontalGroup(
            info_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info_panLayout.createSequentialGroup()
                .addGroup(info_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(info_panLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(info_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(info_panLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel10))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(info_panLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel9))
                    .addGroup(info_panLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel7))
                    .addGroup(info_panLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(info_panLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(info_text_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        info_panLayout.setVerticalGroup(
            info_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_panLayout.createSequentialGroup()
                .addGroup(info_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(info_panLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(info_text_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(info_panLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        base_pan.add(info_pan, "card4");

        login_pan.setMaximumSize(new java.awt.Dimension(1200, 562));
        login_pan.setPreferredSize(new java.awt.Dimension(1200, 562));

        password_Field.setText("jPasswordField1");
        password_Field.setMargin(new java.awt.Insets(2, 10, 2, 2));
        password_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_FieldActionPerformed(evt);
            }
        });

        logintosystem_b.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        logintosystem_b.setText("LOGIN");
        logintosystem_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logintosystem_bActionPerformed(evt);
            }
        });

        username_Field.setText("jFormattedTextField1");
        username_Field.setFocusable(false);
        username_Field.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        username_Field.setMargin(new java.awt.Insets(2, 10, 2, 2));
        username_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_FieldActionPerformed(evt);
            }
        });

        username.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        username.setText("Username");

        password.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        password.setText("Password");

        event_scroll_login_Text.setEditable(false);
        event_scroll_login_Text.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        event_scroll_login_Text.setText("THINGS SCROLL HERE");
        event_scroll_login_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                event_scroll_login_TextActionPerformed(evt);
            }
        });

        importantnews_login_Label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        importantnews_login_Label.setText("                         IMPORTANT EVENTS");
        importantnews_login_Label.setToolTipText("");
        importantnews_login_Label.setAlignmentX(0.5F);
        importantnews_login_Label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        info_login_Text.setEditable(false);
        info_login_Text.setBackground(new java.awt.Color(240, 240, 240));
        info_login_Text.setColumns(20);
        info_login_Text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        info_login_Text.setRows(2);
        info_login_Text.setText("I'VE COME OUT OF THE COMPUTER TO TELL YOU TO STOP\n");
        info_login_Text.setBorder(null);
        info_login_Text.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        info_login_Text.setFocusable(false);
        info_login_Text.setOpaque(false);
        info_login_JScrollPane.setViewportView(info_login_Text);

        FLINDERSUNIVERSITY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comp3751_softwareproto/group1_/knig0033_lanc0035_hunt0065/WINWORD_2018-05-14_15-04-52.png"))); // NOI18N

        javax.swing.GroupLayout rightside_login_panLayout = new javax.swing.GroupLayout(rightside_login_pan);
        rightside_login_pan.setLayout(rightside_login_panLayout);
        rightside_login_panLayout.setHorizontalGroup(
            rightside_login_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightside_login_panLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightside_login_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(event_scroll_login_Text)
                    .addComponent(importantnews_login_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(info_login_JScrollPane))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightside_login_panLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(FLINDERSUNIVERSITY, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        rightside_login_panLayout.setVerticalGroup(
            rightside_login_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightside_login_panLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(FLINDERSUNIVERSITY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(info_login_JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(importantnews_login_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(event_scroll_login_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout login_panLayout = new javax.swing.GroupLayout(login_pan);
        login_pan.setLayout(login_panLayout);
        login_panLayout.setHorizontalGroup(
            login_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_panLayout.createSequentialGroup()
                .addGroup(login_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(login_panLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(login_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password_Field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logintosystem_b, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))
                    .addGroup(login_panLayout.createSequentialGroup()
                        .addGroup(login_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(login_panLayout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(password))
                            .addGroup(login_panLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(username)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(rightside_login_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        login_panLayout.setVerticalGroup(
            login_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_panLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(login_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightside_login_pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(login_panLayout.createSequentialGroup()
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logintosystem_b, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );

        base_pan.add(login_pan, "card5");

        map_pan.setMaximumSize(new java.awt.Dimension(1200, 562));
        map_pan.setPreferredSize(new java.awt.Dimension(1200, 562));

        filter1_map_Check.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        filter1_map_Check.setText("Fliter6");

        fliter2_map_Check.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fliter2_map_Check.setText("Fliter4");

        fliter3_map_Check.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fliter3_map_Check.setText("Fliter3");
        fliter3_map_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fliter3_map_CheckActionPerformed(evt);
            }
        });

        fliter4_map_Check.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fliter4_map_Check.setText("Fliter5");

        fliter5_map_Check.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fliter5_map_Check.setText("Fliter1");

        fliter6_map_Check.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fliter6_map_Check.setText("Fliter2");

        fliters_map_Label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fliters_map_Label.setText("Filters");

        search_map_Form.setText("Hope and dreams");
        search_map_Form.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search_map_Form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_map_FormActionPerformed(evt);
            }
        });

        search_map_B.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search_map_B.setText("Search");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comp3751_softwareproto/group1_/knig0033_lanc0035_hunt0065/chrome_2018-05-14_16-34-48.png"))); // NOI18N

        javax.swing.GroupLayout map_map_panLayout = new javax.swing.GroupLayout(map_map_pan);
        map_map_pan.setLayout(map_map_panLayout);
        map_map_panLayout.setHorizontalGroup(
            map_map_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(map_map_panLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        map_map_panLayout.setVerticalGroup(
            map_map_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );

        javax.swing.GroupLayout map_panLayout = new javax.swing.GroupLayout(map_pan);
        map_pan.setLayout(map_panLayout);
        map_panLayout.setHorizontalGroup(
            map_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(map_panLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(map_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(map_map_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(map_panLayout.createSequentialGroup()
                        .addComponent(fliters_map_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fliter5_map_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fliter6_map_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fliter3_map_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fliter2_map_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fliter4_map_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(filter1_map_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search_map_B, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search_map_Form, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        map_panLayout.setVerticalGroup(
            map_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(map_panLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(map_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, map_panLayout.createSequentialGroup()
                        .addComponent(search_map_Form, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(map_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filter1_map_Check, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fliter3_map_Check, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addComponent(fliter2_map_Check, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addComponent(fliter4_map_Check, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addComponent(fliter5_map_Check, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addComponent(fliter6_map_Check, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addComponent(fliters_map_Label)
                        .addComponent(search_map_B, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(map_map_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        base_pan.add(map_pan, "card6");

        events_pan.setBackground(new java.awt.Color(135, 135, 135));
        events_pan.setMaximumSize(new java.awt.Dimension(1200, 562));
        events_pan.setPreferredSize(new java.awt.Dimension(1200, 562));

        filters_events_Label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        filters_events_Label.setText("Filters");

        filter1_events_Check.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        filter1_events_Check.setText("Fliter6");

        fliter2_events_Check.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fliter2_events_Check.setText("Fliter4");

        fliter3_events_Check.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fliter3_events_Check.setText("Fliter3");
        fliter3_events_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fliter3_events_CheckActionPerformed(evt);
            }
        });

        fliter4_events_Check.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fliter4_events_Check.setText("Fliter5");
        fliter4_events_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fliter4_events_CheckActionPerformed(evt);
            }
        });

        fliter5_events_Check.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fliter5_events_Check.setText("Fliter1");
        fliter5_events_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fliter5_events_CheckActionPerformed(evt);
            }
        });

        fliter6_events_Check.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fliter6_events_Check.setText("Fliter2");

        search_events_Form.setText("Hope and dreams");
        search_events_Form.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search_events_Form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_events_FormActionPerformed(evt);
            }
        });

        search_evnets_B.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search_evnets_B.setText("Search");

        jList1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "INCIDENT | STOLEN ITEM | BAG | CAFE | 12:00PM | SUCESSFULLY FOUND | AS1924", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout events_panLayout = new javax.swing.GroupLayout(events_pan);
        events_pan.setLayout(events_panLayout);
        events_panLayout.setHorizontalGroup(
            events_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(events_panLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(events_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(events_panLayout.createSequentialGroup()
                        .addComponent(filters_events_Label)
                        .addGap(37, 37, 37)
                        .addComponent(fliter5_events_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fliter6_events_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fliter3_events_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fliter2_events_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(fliter4_events_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(filter1_events_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(search_evnets_B, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search_events_Form, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        events_panLayout.setVerticalGroup(
            events_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(events_panLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(events_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(events_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(search_events_Form, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(search_evnets_B, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fliter2_events_Check, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fliter3_events_Check, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fliter6_events_Check, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(events_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fliter4_events_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filter1_events_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(events_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fliter5_events_Check, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filters_events_Label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        base_pan.add(events_pan, "card7");

        getContentPane().add(base_pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 217, 1270, -1));

        FLINSAFE4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        FLINSAFE4.setForeground(new java.awt.Color(255, 255, 255));
        FLINSAFE4.setText("FLINSAFE");
        getContentPane().add(FLINSAFE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, 47));

        FLINSAFE2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        FLINSAFE2.setForeground(new java.awt.Color(255, 255, 255));
        FLINSAFE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SA Uni image.png"))); // NOI18N
        getContentPane().add(FLINSAFE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void security_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_security_BActionPerformed
        //Deleting panels
        base_pan.removeAll();
        base_pan.revalidate();
        
        //Adding panels
        base_pan.add(security_pan);
        base_pan.revalidate();
        base_pan.repaint();
        
    }//GEN-LAST:event_security_BActionPerformed

    private void report_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_BActionPerformed
        //Deleting panels
        base_pan.removeAll();
        base_pan.revalidate();
        
        //Adding panels
        base_pan.add(report_pan);
        base_pan.revalidate();
        base_pan.repaint();
    }//GEN-LAST:event_report_BActionPerformed

    private void login_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_BActionPerformed
        //Deleting panels
        base_pan.removeAll();
        base_pan.revalidate();

        //Adding panels
        base_pan.add(login_pan);
        base_pan.revalidate();
        base_pan.repaint();
    }//GEN-LAST:event_login_BActionPerformed

    private void events_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_events_BActionPerformed
        //Deleting panels
        base_pan.removeAll();
        base_pan.revalidate();

        //Adding panels
        base_pan.add(events_pan);
        base_pan.revalidate();
        base_pan.repaint();
    }//GEN-LAST:event_events_BActionPerformed

    private void username_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_FieldActionPerformed

    private void password_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_FieldActionPerformed

    private void logintosystem_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logintosystem_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logintosystem_bActionPerformed

    private void event_scroll_login_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_event_scroll_login_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_event_scroll_login_TextActionPerformed

    private void callsecurity_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callsecurity_BActionPerformed
        // TODO add your handling code here:
        
        confPop confPop = new confPop();
        confPop.newScreen();
        
    }//GEN-LAST:event_callsecurity_BActionPerformed

    private void fliter3_map_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fliter3_map_CheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fliter3_map_CheckActionPerformed

    private void map_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_map_BActionPerformed
                //Deleting panels
        base_pan.removeAll();
        base_pan.revalidate();
        
        //Adding panels
        base_pan.add(map_pan);
        base_pan.revalidate();
        base_pan.repaint();
    }//GEN-LAST:event_map_BActionPerformed

    private void info_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_BActionPerformed
                //Deleting panels
        base_pan.removeAll();
        base_pan.revalidate();
        
        //Adding panels
        base_pan.add(info_pan);
        base_pan.revalidate();
        base_pan.repaint();
    }//GEN-LAST:event_info_BActionPerformed

    private void search_map_FormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_map_FormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_map_FormActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void fliter3_events_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fliter3_events_CheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fliter3_events_CheckActionPerformed

    private void search_events_FormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_events_FormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_events_FormActionPerformed

    private void fliter4_events_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fliter4_events_CheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fliter4_events_CheckActionPerformed

    private void fliter5_events_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fliter5_events_CheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fliter5_events_CheckActionPerformed

    private void medicalass_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalass_BActionPerformed
        // TODO add your handling code here:
        
       confPop confPop = new confPop();
        confPop.newScreen();
    }//GEN-LAST:event_medicalass_BActionPerformed

    private void emergen_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergen_BActionPerformed
        // TODO add your handling code here:
            
        emergencyType emerg = new emergencyType();
        emerg.emergencyPop();
        
    }//GEN-LAST:event_emergen_BActionPerformed

    private void report_cancel_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_cancel_BActionPerformed
       // report_BActionPerformed(evt);
    }//GEN-LAST:event_report_cancel_BActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_JFrame().setVisible(true);                
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FLINDERSUNIVERSITY;
    private javax.swing.JLabel FLINSAFE2;
    private javax.swing.JLabel FLINSAFE4;
    private javax.swing.JPanel base_pan;
    private javax.swing.JButton callsecurity_B;
    private javax.swing.JTextArea details_report_Text;
    private javax.swing.JScrollPane details_report_jScrollPanel;
    private javax.swing.JButton emergen_B;
    private javax.swing.JTextField event_scroll_login_Text;
    private javax.swing.JScrollPane eventlist_security_JScrollPane;
    private javax.swing.JLabel eventlist_security_Label;
    private javax.swing.JList<String> eventlist_security_List;
    private javax.swing.JButton events_B;
    private javax.swing.JPanel events_pan;
    private javax.swing.JCheckBox filter1_events_Check;
    private javax.swing.JCheckBox filter1_map_Check;
    private javax.swing.JLabel filters_events_Label;
    private javax.swing.JCheckBox fliter2_events_Check;
    private javax.swing.JCheckBox fliter2_map_Check;
    private javax.swing.JCheckBox fliter3_events_Check;
    private javax.swing.JCheckBox fliter3_map_Check;
    private javax.swing.JCheckBox fliter4_events_Check;
    private javax.swing.JCheckBox fliter4_map_Check;
    private javax.swing.JCheckBox fliter5_events_Check;
    private javax.swing.JCheckBox fliter5_map_Check;
    private javax.swing.JCheckBox fliter6_events_Check;
    private javax.swing.JCheckBox fliter6_map_Check;
    private javax.swing.JLabel fliters_map_Label;
    private javax.swing.JLabel importantnews_login_Label;
    private javax.swing.JButton info_B;
    private javax.swing.JScrollPane info_login_JScrollPane;
    private javax.swing.JTextArea info_login_Text;
    private javax.swing.JPanel info_pan;
    private javax.swing.JScrollPane info_security_JScrollPane;
    private javax.swing.JTextArea info_security_Text;
    private javax.swing.JPanel info_text_pan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton login_B;
    private javax.swing.JPanel login_pan;
    private javax.swing.JButton logintosystem_b;
    private javax.swing.JButton map_B;
    private javax.swing.JPanel map_map_pan;
    private javax.swing.JPanel map_pan;
    private javax.swing.JButton medicalass_B;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField password_Field;
    private javax.swing.JButton report_B;
    private javax.swing.JButton report_cancel_B;
    private javax.swing.JPanel report_pan;
    private javax.swing.JButton report_submit_B;
    private javax.swing.JPanel rightside_login_pan;
    private javax.swing.JFormattedTextField search_events_Form;
    private javax.swing.JButton search_evnets_B;
    private javax.swing.JButton search_map_B;
    private javax.swing.JFormattedTextField search_map_Form;
    private javax.swing.JButton security_B;
    private javax.swing.JPanel security_pan;
    private javax.swing.JLabel username;
    private javax.swing.JFormattedTextField username_Field;
    // End of variables declaration//GEN-END:variables
}
